export const LOGIN = 'LOGIN';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const FETCH_MENTORS = 'FETCH_MENTORS';
export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const FETCH_SINGLE_USER = 'FETCH_SINGLE_USER'
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_IMAGE = 'UPDATE_USER_IMAGE';
export const UPDATE_USER_IMAGE_LOADING = 'UPDATE_USER_IMAGE_LOADING';
export const UPDATE_PROFILE_LOADING = 'UPDATE_PROFILE_LOADING'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const ADD_COURSE = 'ADD_COURSE';
export const ALL_COURSES = 'ALL_COURSES';
export const ENROLL_COURSE = 'ENROLL_COURSE';

